apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
spec:
  podSelector: {}        # Áp dụng cho tất cả pod trong namespace
  policyTypes:
    - Egress
  egress:
    - {}                 # Không giới hạn IP, port => cho phép đi ra ngoài hoàn toàn